services:
  backend:
    build: ./api
    container_name: scraper-backend
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./api:/app
      - scraper_data:/app/scraper_data
    env_file:
      - ./api/.env.development
    environment:
      - NODE_OPTIONS=--max-old-space-size=460
      - DATA_DIR=/app/scraper_data
      - SCRAPER_VOLUME_NAME=scraper_data
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - scraper-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  scraper-builder:
    build: ./google-maps-scraper
    image: scraper-image:latest
    container_name: scraper-image-builder
    entrypoint: [ "/bin/true" ]
    profiles: [ "build-only" ]

volumes:
  scraper_data:
    name: scraper_data

networks:
  scraper-network:
    driver: bridge
